import { IconConfig, IconResourceType } from '@spartacus/storefront';

export enum ICONS {
  SEARCH = 'SEARCH',
  CLOSE = 'CLOSE',
  USER = 'USER',
  MINICART = 'MINICART',
  WISHLIST = 'WISHLIST',
  WISHLIST_FULL = 'WISHLIST_FULL',
  SHOPPING_BAG = 'SHOPPING_BAG',
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  PINTEREST = 'PINTEREST',
  TWITTER = 'TWITTER',
  PAYPAL = 'PAYPAL',
  MASTERCARD = 'MASTERCARD',
  VISA = 'VISA',
  GOOGLEPAY = 'GOOGLEPAY',
  AMERICANEXPRESS = 'AMERICANEXPRESS',
  APPLEPAY = 'APPLEPAY',
  ARROWDOWN = 'ARROWDOWN',
  CHEVRON_DOWN = 'CHEVRON_DOWN',
  CHEVRON_UP = 'CHEVRON_UP',
  CHEVRON_RIGHT = 'CHEVRON_RIGHT',
  CHEVRON_LEFT = 'CHEVRON_LEFT',
  SLIDERS = 'SLIDERS',
  GRID_VIEW = 'GRID_VIEW',
  LIST_VIEW = 'LIST_VIEW',
  ARROW_LEFT = 'ARROW_LEFT',
  ARROW_RIGHT = 'ARROW_RIGHT',
  FA_ARROW_RIGHT_CIRCLE = 'FA_ARROW_RIGHT_CIRCLE',
  FA_CHECK_CIRCLE = 'FA_CHECK_CIRCLE',
  FA_EXCLAMATION_CIRCLE = 'FA_EXCLAMATION_CIRCLE',
  FA_EXTERNAL_LINK = 'FA_EXTERNAL_LINK',
  DOWNLOAD = 'DOWNLOAD',
  DOCUMENT = 'DOCUMENT',
  CHAT = 'CHAT',
  PRINTER = 'PRINTER',
  HINT_LIGHT_BULB = 'HINT_LIGHT_BULB',
  CLIPBOARD_CHECK = 'CLIPBOARD_CHECK',
  CREDIT_CARD = 'CREDIT_CARD',
  MAP_PIN = 'MAP_PIN',
  BOOK = 'BOOK',
  BANKCARD = 'BANKCARD',
  LOGOUT = 'LOGOUT',
  ADD = 'ADD',
  INFO_CIRCLE = 'INFO_CIRCLE',
  CHECK = 'CHECK',
  DASHBOARD = 'DASHBOARD',
  PENCIL = 'PENCIL',
  TRASHCAN = 'TRASHCAN',
  CHECK_CIRCLE = 'CHECK_CIRCLE',
  CLIPBOARD_LIST = 'CLIPBOARD_LIST',
  CROSS_CIRCLE = 'CROSS_CIRCLE',
  CHECKMARK_CIRCLE = 'CHECKMARK_CIRCLE',
  QUESTION_CIRCLE = 'QUESTION_CIRCLE',
  CALENDAR = 'CALENDAR',
  LINKEDIN = 'LINKEDIN',
  YOUTUBE = 'YOUTUBE',
  ORDER_HISTORY_BDCRMB = 'ORDER_HISTORY_BDCRMB',
  MY_PROFILE_BDCRMB = 'MY_PROFILE_BDCRMB',
  ADDRESS_BOOK_BDCRMB = 'ADDRESS_BOOK_BDCRMB',
  WISHLIST_BDCRMB = 'WISHLIST_BDCRMB',
  CHECKOUT_BDCRMB = 'CHECKOUT_BDCRMB',
  CART_BDCRMB = 'CART_BDCRMB',
  PIE_CHART = 'PIE_CHART',
  SETTINGS = 'SETTINGS',
  INFO = 'INFO',
  NOTIFICATIONS = 'NOTIFICATIONS',
  WARNING = 'WARNING',
}

export const iconConfig: IconConfig = {
  icon: {
    symbols: {
      SEARCH: 'search',
      CLOSE: 'close',
      USER: 'user',
      MINICART: 'mini-cart',
      WISHLIST: 'wish-list',
      WISHLIST_FULL: 'wish-list-full',
      SHOPPING_BAG: 'shopping-bag',
      FACEBOOK: 'facebook',
      INSTAGRAM: 'instagram',
      PINTEREST: 'pinterest',
      TWITTER: 'twitter',
      PAYPAL: 'paypal',
      MASTERCARD: 'mastercard',
      VISA: 'visa',
      GOOGLEPAY: 'googlepay',
      AMERICANEXPRESS: 'americanexpress',
      APPLEPAY: 'applepay',
      ARROWDOWN: 'arrow-down',
      CHEVRON_DOWN: 'chevron-down',
      CHEVRON_UP: 'chevron-up',
      CHEVRON_RIGHT: 'chevron-right',
      CHEVRON_LEFT: 'chevron-left',
      SLIDERS: 'sliders',
      GRID_VIEW: 'grid-view',
      LIST_VIEW: 'list-view',
      ARROW_LEFT: 'arrow-left',
      ARROW_RIGHT: 'arrow-right',
      FA_ARROW_RIGHT_CIRCLE: 'fas fa-arrow-circle-right',
      FA_CHECK_CIRCLE: 'fas fa-check-circle',
      FA_EXCLAMATION_CIRCLE: 'fas fa-exclamation-circle',
      FA_EXTERNAL_LINK: 'fas fa-external-link-alt',
      DOWNLOAD: 'download',
      DOCUMENT: 'document',
      CHAT: 'chat',
      CLIPBOARD_CHECK: 'clipboard-check',
      CREDIT_CARD: 'credit-card',
      MAP_PIN: 'map-pin',
      PRINTER: 'printer',
      HINT_LIGHT_BULB: 'hint-light-bulb',
      INFO_CIRCLE: 'info-circle',
      BOOK: 'book',
      BANKCARD: 'bank-card',
      LOGOUT: 'logout',
      ADD: 'add',
      CHECK: 'check',
      DASHBOARD: 'dashboard',
      CROSS_CIRCLE: 'cross-circle',
      CHECKMARK_CIRCLE: 'checkmark-circle',
      QUESTION_CIRCLE: 'question-circle',
      PENCIL: 'pencil',
      TRASHCAN: 'trashcan',
      CHECK_CIRCLE: 'check-circle',
      CLIPBOARD_LIST: 'clipboard-list',
      CALENDAR: 'calendar',
      LINKEDIN: 'linkedin',
      YOUTUBE: 'youtube',
      ORDER_HISTORY_BDCRMB: 'order-history-bdcrmb',
      MY_PROFILE_BDCRMB: 'my-profile-bdcrmb',
      ADDRESS_BOOK_BDCRMB: 'address-book-bdcrmb',
      WISHLIST_BDCRMB: 'wishlist-bdcrmb',
      CHECKOUT_BDCRMB: 'checkout-bdcrmb',
      CART_BDCRMB: 'cart-bdcrmb',
      SETTINGS: 'settings',
      PIE_CHART: 'pie-chart',
      INFO: 'info',
      NOTIFICATIONS: 'notifications',
      WARNING: 'warning',
    },
    resources: [
      {
        type: IconResourceType.LINK,
        url: 'https://use.fontawesome.com/releases/v5.8.1/css/all.css',
      },
      {
        type: IconResourceType.SVG,
        url: './assets/icons/sprite.svg',
        types: [
          ICONS.SEARCH,
          ICONS.CLOSE,
          ICONS.USER,
          ICONS.MINICART,
          ICONS.WISHLIST,
          ICONS.WISHLIST_FULL,
          ICONS.SHOPPING_BAG,
          ICONS.SEARCH,
          ICONS.CLOSE,
          ICONS.CLOSE,
          ICONS.FACEBOOK,
          ICONS.INSTAGRAM,
          ICONS.PINTEREST,
          ICONS.TWITTER,
          ICONS.PAYPAL,
          ICONS.MASTERCARD,
          ICONS.VISA,
          ICONS.GOOGLEPAY,
          ICONS.AMERICANEXPRESS,
          ICONS.APPLEPAY,
          ICONS.SEARCH,
          ICONS.CLOSE,
          ICONS.USER,
          ICONS.MINICART,
          ICONS.ARROWDOWN,
          ICONS.CHEVRON_DOWN,
          ICONS.CHEVRON_UP,
          ICONS.CHEVRON_RIGHT,
          ICONS.CHEVRON_LEFT,
          ICONS.SLIDERS,
          ICONS.GRID_VIEW,
          ICONS.LIST_VIEW,
          ICONS.ARROW_LEFT,
          ICONS.ARROW_RIGHT,
          ICONS.PRINTER,
          ICONS.HINT_LIGHT_BULB,
          ICONS.DOWNLOAD,
          ICONS.DOCUMENT,
          ICONS.CHAT,
          ICONS.CLIPBOARD_CHECK,
          ICONS.CREDIT_CARD,
          ICONS.MAP_PIN,
          ICONS.INFO_CIRCLE,
          ICONS.BOOK,
          ICONS.BANKCARD,
          ICONS.LOGOUT,
          ICONS.ADD,
          ICONS.CHECK,
          ICONS.DASHBOARD,
          ICONS.PENCIL,
          ICONS.TRASHCAN,
          ICONS.CHECK_CIRCLE,
          ICONS.CLIPBOARD_LIST,
          ICONS.CROSS_CIRCLE,
          ICONS.CHECKMARK_CIRCLE,
          ICONS.QUESTION_CIRCLE,
          ICONS.CALENDAR,
          ICONS.LINKEDIN,
          ICONS.YOUTUBE,
          ICONS.ORDER_HISTORY_BDCRMB,
          ICONS.MY_PROFILE_BDCRMB,
          ICONS.ADDRESS_BOOK_BDCRMB,
          ICONS.WISHLIST_BDCRMB,
          ICONS.CHECKOUT_BDCRMB,
          ICONS.CART_BDCRMB,
          ICONS.SETTINGS,
          ICONS.PIE_CHART,
          ICONS.INFO,
          ICONS.NOTIFICATIONS,
          ICONS.WARNING,
        ],
      },
    ],
  },
};
